# Generated by Django 3.2.9 on 2021-12-06 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='modificacao',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='modificacao',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='modificacao',
            new_name='modificado',
        ),
    ]
