# Generated by Django 3.2.9 on 2021-12-06 01:16

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211205_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='get_file_path', verbose_name='Imagem'),
        ),
    ]
